version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["quasar", "dev"]
