version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - $GOPATH/src/compras/backend:/app
    depends_on:
      - mongodb
    working_dir: /app
    command: air

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysqldb:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    depends_on:
      mysqldb:
        condition: service_healthy
    extra_hosts:
      - 'host.docker.internal:172.31.0.1'
  
  mysqldb:
    image: mysql:8.0.30-debian
    volumes:
      - ./data/mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
